### ISSUE TITLE
Keyword documentation webpage goes to 404 error

### ISSUE THREAD

**Issue by artem-zinin** [MarketSquare/robotframework-SikuliLibrary#192]
The keyword documentation hyperlink is broken, or the target webpage is down.

Try the link: http://rainmanwy.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html

This is what I get every time I click the link to check Keyword documentation:

![Image](https://github.com/user-attachments/assets/20221887-42b2-4945-ab1a-f9bef54be212)

**Comment by HelioGuilherme66** [comment]
@artem-zinin This will be fixed soon. For now you should use the new URL at https://marketsquare.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html

**Comment by HelioGuilherme66** [comment]
Fixed

**Comment by artem-zinin** [comment]
> [@artem-zinin](https://github.com/artem-zinin) This will be fixed soon. For now you should use the new URL at https://marketsquare.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html

Both this link and the original link still do not work. I still get the 404 error.

**Comment by HelioGuilherme66** [comment]
@artem-zinin Links are working from the README.md page, directly to the code (the directory name `doc` was changed to `docs`):
http://marketsquare.github.io/robotframework-SikuliLibrary/docs/SikuliLibrary.html
